@startuml Диаграмма последовательности чтения списка заказов в MES
actor "Оператор" as op
participant "Frontend" as front
participant "Backend" as back
participant "Кеш" as cache
participant "БД" as db

== Получение списка заказов ==
op -> front: Работа со страницей списка заказов с применением фильтрации и пагинации
front -> back: Отправка запроса к MES API на получение списка заказов
back -> cache: Проверка списка заказов с учетом параметров на наличие в кеше

alt Данные есть в кеше
    cache --> back: возврат списка заказов из кеша
else Данных нет в кеше
    back -> db: Получение списка заказов
    db --> back: Возврат списка заказов из БД
    back -> cache: Запись результатов в кеш
end

back --> front: Возврат результатов работы API
front --> op: Отображение результатов оператору

== Изменение статуса заказа ==

op -> front: Изменение оператором статуса заказа
front -> back: Отправка запроса к MES API на изменение статуса заказа
back -> db: Обновление статуса заказа
db --> back: Возврат результата обновления
back -> cache: Инвалидация кеша списка заказов и кеша детальной информации о заказе
back --> front: Возврат результатов работы API
front --> op: Отображение результатов оператору

@enduml